import React from 'react';
import GroasisUtility from '../../GroasisUtility';

const LegendInfo = {
  [GroasisUtility.layers.tile.soilClasses]: null,
  [GroasisUtility.layers.tile.organic]: 'Soil organic matter, which is usually considered to contain approximately 58% organic carbon, consists of partially decayed plant residues, microorganisms and the by-products of microbial growth and decomposition. It is a key component of soil as it influences its structure, aggregate stability, nutrient availability, water retention and resilience. Through these properties, soils contribute to ecosystem dynamics and provide ecosystem services vital to human activities, such as food production or the prevention of land degradation.',
  [GroasisUtility.layers.tile.clay]: 'These soils have a good ability to transport water by capillary action from deep layers but the rate is slow, so plant water requirements are not met through capillary water. These soils are darker in colour and soil aggregation is more distinct. Aggregation decreases the risk of crusting. These soils must be tilled at the correct water content in order to be easily cultivated. There is a risk of clodding if conditions are too dry, or of smearing if they are too wet. These soils have a good ability to improve their structure through the action of climate, roots etc.',
  [GroasisUtility.layers.tile.sand]: 'Sand soils are often dry, nutrient deficient and fast-draining. They have little (or no) ability to transport water from deeper layers through capillary transport. Therefore, tillage of sandy soils in the spring should be kept to a minimum in order to retain moisture in the seedbed. The nutrient- and water-holding capacity of sand soils can be improved through adding organic material.',
  [GroasisUtility.layers.tile.coarse]: 'A coarse fragment is any primary soil particle with a nominal diameter greater than 2 millimeters. Some definitions exclude boulders, which are larger than 250 millimeters. Particles that are more than 2 millimeters in diameter are not included in chemical, mineralogical, and some physical analyses, and they are called coarse fragments.',
  [GroasisUtility.layers.tile.ph]: 'Why is pH in soil important? The relative acidity or alkalinity of soil is indicated by its pH. A pH of 7 indicates a neutral soil. The pH is important because it influences the availability of essential nutrients. Most horticultural crops will grow satisfactorily in soils having a pH between 6 (slightly acid) and 7.5 (slightly alkaline). pH 7 to 0 the soil is increasingly more acidic and from pH 7 to 14 the soil is increasingly more alkaline. Most soils have pH values between 3.5 and 10. In higher rainfall areas the natural pHof soils typically ranges from 5 to 7, while in drier areas the range is 6.5 to 9. Soils can be classified according to their pH value: 6.5 to 7.5—neutral.',
}

export default LegendInfo;